Repository aayushi195/ReachAPI, pull requests merged in 2019-02, with the labels that each got.

#8 Added model for SWAP and developed creat API
  src/edu/asu/heal/reachv3/api/models/SwapActivityInstance.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#10 Added model and create API for DailyDiary activity instance.
  src/edu/asu/heal/reachv3/api/models/DailyDiaryActivityInstance.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#11 Task#453
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#6 Task#423 - New mongodb collection for the standUp activity
  Sample Databases/healdb/standUpSituations.bson
  Sample Databases/healdb/standUpSituations.metadata.json
Labels: backend, refactoring

#13 Task#425
  src/edu/asu/heal/core/api/dao/DAO.java
  src/edu/asu/heal/core/api/dao/impl/MongoDBDAO.java
  src/edu/asu/heal/reachv3/api/models/StandUpActivityInstance.java
  src/edu/asu/heal/reachv3/api/models/StandUpOption.java
  src/edu/asu/heal/reachv3/api/models/StandUpQuestion.java
  src/edu/asu/heal/reachv3/api/models/StandUpResponse.java
  src/edu/asu/heal/reachv3/api/models/StandUpSituation.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#15 Task#509
  src/edu/asu/heal/core/api/dao/DAO.java
  src/edu/asu/heal/core/api/dao/impl/MongoDBDAO.java
  src/edu/asu/heal/reachv3/api/models/WorryHeadsActivityInstance.java
Labels: backend, refactoring

#16 Task#428 Added code for update API of standup activity
  src/edu/asu/heal/core/api/dao/impl/MongoDBDAO.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#18 Issue#17 Get API issue has been resolved by removing set situation in…
  src/edu/asu/heal/core/api/dao/impl/MongoDBDAO.java
Labels: bug

#19 Task#431 - Mongodb collection for face it challenges
  Sample Databases/healdb/faceItChallenges.bson
  Sample Databases/healdb/faceItChallenges.metadata.json
Labels: backend, refactoring

#20 Task#471 Create API for emotion activity instance
  src/edu/asu/heal/core/api/dao/impl/MongoDBDAO.java
  src/edu/asu/heal/reachv3/api/models/EmotionActivityInstance.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#23 Task#434 - Create API for FaceIT activity
  src/edu/asu/heal/core/api/dao/DAO.java
  src/edu/asu/heal/core/api/dao/impl/MongoDBDAO.java
  src/edu/asu/heal/reachv3/api/models/FaceItActivityInstance.java
  src/edu/asu/heal/reachv3/api/models/FaceItChallenges.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#24 Task#437 - Get API for FaceIT Activity
  src/edu/asu/heal/core/api/dao/impl/MongoDBDAO.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#25 Task#438 - Update API for faceIt activity
  src/edu/asu/heal/reachv3/api/models/FaceItChallenges.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#29 Task#403
  apidocs/vendor/polyfill 2.js
  apidocs/vendor/prettify 2.css
  apidocs/vendor/prettify/lang-clj 2.js
  apidocs/vendor/prettify/lang-el 2.js
  apidocs/vendor/prettify/lang-lasso 2.js
  apidocs/vendor/prettify/lang-lgt 2.js
  apidocs/vendor/prettify/lang-logtalk 2.js
  apidocs/vendor/prettify/lang-ls 2.js
  apidocs/vendor/prettify/lang-proto 2.js
  apidocs/vendor/prettify/lang-r 2.js
  apidocs/vendor/prettify/lang-rust 2.js
  apidocs/vendor/prettify/lang-ss 2.js
  apidocs/vendor/prettify/lang-tcl 2.js
  apidocs/vendor/prettify/lang-tex 2.js
  apidocs/vendor/prettify/lang-vhd 2.js
  apidocs/vendor/prettify/lang-vhdl 2.js
  apidocs/vendor/prettify/lang-xquery 2.js
  apidocs/vendor/prettify/lang-yaml 2.js
  apidocs/vendor/prettify/lang-yml 2.js
  apidocs/vendor/prettify/prettify 2.css
  apidocs/vendor/webfontloader 2.js
  src/edu/asu/heal/core/api/resources/ActivityInstanceResource.java
  src/edu/asu/heal/core/api/resources/ActivityResource.java
  src/edu/asu/heal/core/api/resources/DomainResource.java
  src/edu/asu/heal/core/api/resources/LoggerResource.java
  src/edu/asu/heal/core/api/resources/PatientResource.java
  src/edu/asu/heal/core/api/resources/TrialsResource.java
Labels: refactoring

#32 Task#569
  .gitignore
  build.properties
  build.xml
  src/edu/asu/heal/core/api/dao/DAO.java
  src/edu/asu/heal/core/api/dao/impl/MongoDBDAO.java
  src/edu/asu/heal/core/api/resources/ActivityInstanceResource.java
  src/edu/asu/heal/core/api/resources/DomainResource.java
  src/edu/asu/heal/reachv3/api/service/ReachService.java
Labels: backend, refactoring

#33 Task#570
  Sample Databases/healdb/domains.bson
  Sample Databases/healdb/domains.metadata.json
Labels: backend, refactoring
